version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
  simulator:
    build: ./simulator
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
